version: "3.9"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.3
    command: start-dev --features=preview
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=keycloak
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_LOG_LEVEL=INFO
      # - KC_DB_PASSWORD=password
      # - KC_DB_USERNAME=keycloak
      # - KC_DB=postgres
      # - KC_DB_URL_HOST=postgres
      # - KC_DB_URL_PORT=5432
      # - KC_DB_URL_DATABASE=keycloak
    # depends_on:
    #   - postgres
  # postgres:
  #   environment:
  #     - POSTGRES_DB=keycloak
  #     - POSTGRES_USER=keycloak
  #     - POSTGRES_PASSWORD=password
  #   image: postgres:12
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - postgres:/var/lib/postgresql
# volumes:
#   postgres:
